---

- name: Install clickhouse
  hosts: clickhouse
  roles:
  - clickhouse

- name: Install vector
  hosts: vector01
  roles:
    - role: vector-role

- name: Install lighthouse
  hosts: light01
  roles:
    - role: lighthouse-role
