---
- name: Install clickhouse
  hosts: clickhouse
  roles:
  - click-role

- name: Install vector
  hosts: vector01
  roles:
  - vector-role

- name: Install lighthouse
  hosts: light01
  roles:
  - lighthouse-role
